/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.alessandromarconi.calcolatrice;

/**
 *
 * @author alessandro.marconi
 */
public class CalcolatriceFrame extends javax.swing.JFrame {

    double n1 = 0;
    double n2 = 0;
    double ris = 0;
    int x = 0; //x=1 somma, x=2 sottrazione, x=3 molti, x=4 divisione
    /**
     * Creates new form CalcolatriceFrame
     */
    public CalcolatriceFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        schermoField = new javax.swing.JTextField();
        btnOtto = new javax.swing.JButton();
        btnSette = new javax.swing.JButton();
        btnNove = new javax.swing.JButton();
        btnQuattro = new javax.swing.JButton();
        btnCinque = new javax.swing.JButton();
        btnSei = new javax.swing.JButton();
        btnUno = new javax.swing.JButton();
        btnDue = new javax.swing.JButton();
        btnTre = new javax.swing.JButton();
        btnDiviso = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnMoltiplicazione = new javax.swing.JButton();
        btnSottrazione = new javax.swing.JButton();
        btnSomma = new javax.swing.JButton();
        btnUguale = new javax.swing.JButton();
        btnIndietro = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btnVirgola = new javax.swing.JButton();
        btnPotenza = new javax.swing.JButton();
        btnRadice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calcolatrice");
        setLocation(new java.awt.Point(400, 300));
        setResizable(false);

        schermoField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        schermoField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        schermoField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        schermoField.setEnabled(false);
        schermoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schermoFieldActionPerformed(evt);
            }
        });

        btnOtto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOtto.setText("8");
        btnOtto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOttoActionPerformed(evt);
            }
        });

        btnSette.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSette.setText("7");
        btnSette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetteActionPerformed(evt);
            }
        });

        btnNove.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNove.setText("9");
        btnNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoveActionPerformed(evt);
            }
        });

        btnQuattro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnQuattro.setText("4");
        btnQuattro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuattroActionPerformed(evt);
            }
        });

        btnCinque.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCinque.setText("5");
        btnCinque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCinqueActionPerformed(evt);
            }
        });

        btnSei.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSei.setText("6");
        btnSei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeiActionPerformed(evt);
            }
        });

        btnUno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUno.setText("1");
        btnUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnoActionPerformed(evt);
            }
        });

        btnDue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDue.setText("2");
        btnDue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDueActionPerformed(evt);
            }
        });

        btnTre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTre.setText("3");
        btnTre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreActionPerformed(evt);
            }
        });

        btnDiviso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDiviso.setText("÷");
        btnDiviso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisoActionPerformed(evt);
            }
        });

        btnZero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnZero.setText("0");
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnMoltiplicazione.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMoltiplicazione.setText("×");
        btnMoltiplicazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoltiplicazioneActionPerformed(evt);
            }
        });

        btnSottrazione.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSottrazione.setText("-");
        btnSottrazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSottrazioneActionPerformed(evt);
            }
        });

        btnSomma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSomma.setText("+");
        btnSomma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSommaActionPerformed(evt);
            }
        });

        btnUguale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUguale.setText("=");
        btnUguale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUgualeActionPerformed(evt);
            }
        });

        btnIndietro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnIndietro.setText("←");
        btnIndietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndietroActionPerformed(evt);
            }
        });

        btnCE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });

        btnVirgola.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVirgola.setText(".");
        btnVirgola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVirgolaActionPerformed(evt);
            }
        });

        btnPotenza.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        btnPotenza.setText("x^");
        btnPotenza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotenzaActionPerformed(evt);
            }
        });

        btnRadice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRadice.setText("√");
        btnRadice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(schermoField)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JPanelLayout.createSequentialGroup()
                                .addComponent(btnRadice, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnIndietro, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(JPanelLayout.createSequentialGroup()
                                    .addComponent(btnSette, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnOtto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnNove, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(JPanelLayout.createSequentialGroup()
                                    .addComponent(btnQuattro, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnCinque, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnSei, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(JPanelLayout.createSequentialGroup()
                                    .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnUno, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnPotenza, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(JPanelLayout.createSequentialGroup()
                                            .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnVirgola, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(JPanelLayout.createSequentialGroup()
                                            .addComponent(btnDue, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnTre, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMoltiplicazione, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSottrazione, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUguale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSomma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDiviso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addComponent(schermoField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDiviso, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIndietro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRadice, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOtto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSette, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNove, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMoltiplicazione, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCinque, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuattro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSei, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSottrazione, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDue, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTre, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSomma, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUguale, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVirgola, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPotenza, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void schermoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schermoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schermoFieldActionPerformed

    private void btnOttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOttoActionPerformed
        schermoField.setText(schermoField.getText() + "8");
    }//GEN-LAST:event_btnOttoActionPerformed

    private void btnNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoveActionPerformed
        schermoField.setText(schermoField.getText() + "9");
    }//GEN-LAST:event_btnNoveActionPerformed

    private void btnSetteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetteActionPerformed
        schermoField.setText(schermoField.getText() + "7");
    }//GEN-LAST:event_btnSetteActionPerformed

    private void btnQuattroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuattroActionPerformed
        schermoField.setText(schermoField.getText() + "4");
    }//GEN-LAST:event_btnQuattroActionPerformed

    private void btnCinqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCinqueActionPerformed
        schermoField.setText(schermoField.getText() + "5");
    }//GEN-LAST:event_btnCinqueActionPerformed

    private void btnSeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeiActionPerformed
        schermoField.setText(schermoField.getText() + "6");
    }//GEN-LAST:event_btnSeiActionPerformed

    private void btnUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnoActionPerformed
        schermoField.setText(schermoField.getText() + "1");
    }//GEN-LAST:event_btnUnoActionPerformed

    private void btnDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDueActionPerformed
        schermoField.setText(schermoField.getText() + "2");
    }//GEN-LAST:event_btnDueActionPerformed

    private void btnTreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreActionPerformed
        schermoField.setText(schermoField.getText() + "3");
    }//GEN-LAST:event_btnTreActionPerformed

    private void btnDivisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisoActionPerformed
        n1 = Double.parseDouble(schermoField.getText());
        schermoField.setText("");
        x = 4;
    }//GEN-LAST:event_btnDivisoActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        schermoField.setText(schermoField.getText() + "0");
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnMoltiplicazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoltiplicazioneActionPerformed
        n1 = Double.parseDouble(schermoField.getText());
        schermoField.setText("");
        x = 3;
    }//GEN-LAST:event_btnMoltiplicazioneActionPerformed

    private void btnSottrazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSottrazioneActionPerformed
        n1 = Double.parseDouble(schermoField.getText());
        schermoField.setText("");
        x = 2;
    }//GEN-LAST:event_btnSottrazioneActionPerformed

    private void btnSommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSommaActionPerformed
        n1 = Double.parseDouble(schermoField.getText());
        schermoField.setText("");
        x = 1;
    }//GEN-LAST:event_btnSommaActionPerformed

    private void btnUgualeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUgualeActionPerformed
        calcola();
    }//GEN-LAST:event_btnUgualeActionPerformed

    private void btnIndietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndietroActionPerformed
        String indietro = schermoField.getText();
        indietro = indietro.substring(0, indietro.length() - 1);
        schermoField.setText(indietro);
    }//GEN-LAST:event_btnIndietroActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        schermoField.setText("");
        x = 0;
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnVirgolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVirgolaActionPerformed
        schermoField.setText(schermoField.getText() + ".");
    }//GEN-LAST:event_btnVirgolaActionPerformed

    private void btnPotenzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotenzaActionPerformed
        n1 = Double.parseDouble(schermoField.getText());
        schermoField.setText("");
        x = 5;
    }//GEN-LAST:event_btnPotenzaActionPerformed

    private void btnRadiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadiceActionPerformed
        n1 = Double.parseDouble(schermoField.getText());
        schermoField.setText("");
        ris = Math.sqrt(n1);
        schermoField.setText(Double.toString(ris));
    }//GEN-LAST:event_btnRadiceActionPerformed

    public void calcola()
    {
        n2 = Double.parseDouble(schermoField.getText());
        switch(x)
        {
            case 0:
                schermoField.setText(schermoField.getText());
                break;
            case 1:
                ris = n1 + n2;
                schermoField.setText("");
                schermoField.setText(Double.toString(ris));
                break;
            case 2:
                ris = n1 - n2;
                schermoField.setText("");
                schermoField.setText(Double.toString(ris));
                break;
            case 3:
                ris = n1 * n2;
                schermoField.setText("");
                schermoField.setText(Double.toString(ris));
                break;
            case 4:
                ris = n1 / n2;
                schermoField.setText("");
                schermoField.setText(Double.toString(ris));
                break;
            case 5:
                ris = Math.pow(n1, n2);
                schermoField.setText(Double.toString(ris));
                break;
            default:
                break;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcolatriceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcolatriceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcolatriceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcolatriceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcolatriceFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnCinque;
    private javax.swing.JButton btnDiviso;
    private javax.swing.JButton btnDue;
    private javax.swing.JButton btnIndietro;
    private javax.swing.JButton btnMoltiplicazione;
    private javax.swing.JButton btnNove;
    private javax.swing.JButton btnOtto;
    private javax.swing.JButton btnPotenza;
    private javax.swing.JButton btnQuattro;
    private javax.swing.JButton btnRadice;
    private javax.swing.JButton btnSei;
    private javax.swing.JButton btnSette;
    private javax.swing.JButton btnSomma;
    private javax.swing.JButton btnSottrazione;
    private javax.swing.JButton btnTre;
    private javax.swing.JButton btnUguale;
    private javax.swing.JButton btnUno;
    private javax.swing.JButton btnVirgola;
    private javax.swing.JButton btnZero;
    private javax.swing.JTextField schermoField;
    // End of variables declaration//GEN-END:variables
}
